name: Release

on:
  workflow_run:
    workflows: ["test"]
    branches: ["main"]
    types:
      - completed

jobs:
  release:
    name: Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run semantic release
        run: |
          npm install --save-dev semantic-release@latest
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}