name: test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: test
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          MSSQL_SA_PASSWORD: "Password123"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: get dependencies
        run: go get -v -t -d ./...
      - name: test code
        run: go test ./...